apiVersion: v1
kind: PersistentVolume
metadata:
  name: httplog
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /opt/tmp/pv01
