apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: httpdlog-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
status: {}
